-- Shanvi Insurance Services: Supabase leads table
-- Run this once in Supabase SQL Editor.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  mobile text not null,
  email text,
  insurance_type text not null,
  message text,
  vehicle_number text,
  source text default 'website enquiry',
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

-- Public website visitors need INSERT only. Do not expose SELECT to anon/public users.
drop policy if exists "Public can submit leads" on public.leads;
create policy "Public can submit leads"
on public.leads
for insert
to anon, authenticated
with check (true);
